import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import HomePage from '@/Components/Homepage'
import Button from "@/Components/Button";
const inter = Inter({ subsets: ["latin"] });
import Script from "next/script";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
        {/* <Button /> */}
      </main>
      <Script src="https://kit.fontawesome.com/a865f27d9f.js" crossOrigin="anonymous"></Script> 
    </>
  );
}
